development:
  adapter: postgresql
  database: pv_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: pv_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: pv_production
  pool: 5
  timeout: 5000
